name: Publish to PyPI

on:
    release:
        types: [published]
    workflow_dispatch:
        inputs:
            test_pypi:
                description: 'Publish to Test PyPI instead of PyPI'
                required: false
                default: false
                type: boolean

jobs:
    publish:
        runs-on: ubuntu-latest
        permissions:
            id-token: write # Required for trusted publishing
            contents: read

        steps:
            - uses: actions/checkout@v4

            - name: Set up Python
              uses: actions/setup-python@v5
              with:
                  python-version: '3.12'

            - name: Install uv
              uses: astral-sh/setup-uv@v3
              with:
                  version: 'latest'

            - name: Build package
              run: uv build

            - name: Publish to Test PyPI
              if: github.event.inputs.test_pypi == 'true'
              uses: pypa/gh-action-pypi-publish@release/v1
              with:
                  repository-url: https://test.pypi.org/legacy/

            - name: Publish to PyPI
              if: github.event.inputs.test_pypi != 'true'
              uses: pypa/gh-action-pypi-publish@release/v1
